main: com.sudano.sdscreenshare.Main
name: sdScreenShare
version: develop
authors: [Carlos Henrique#0240]
description: Versão 2.0 do Plugin sdScreenShare.
commands:
   screenshare:
    aliases: [ss]