main: com.github.crlshnrrq.screenshareplugin.Main
name: ScreenSharePlugin
version: 2.7
authors: [Carlos Henrique#0240]
description: |
  Sistema de ScreenShare customizável, seguro e estável.
  Disponível para versões 1.7x e 1.8x
commands:
   screenshare:
    aliases: [ss]